services:
  financas_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: financas_control_v2
    container_name: financas_control_v2
    ports:
      - "8501:8501"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_SCHEMA: ${DB_SCHEMA}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      CLASSIFICATION_MODEL_API: ${CLASSIFICATION_MODEL_API}
    restart: unless-stopped
